benchmarks: add build options
Running pip install in the container without any options
results in errors due to missing packages.

```
$ ./holohub run-container  endoscopy_tool_tracking
...
xxx@yyy:~$ python3 benchmarks/holoscan_flow_benchmarking/benchmark.py -a  endoscopy_tool_tracking  -r 3 -i 3 -m 200     --sched greedy     -d myoutputs
Traceback (most recent call last):
  File "/workspace/holohub/benchmarks/holoscan_flow_benchmarking/benchmark.py", line 27, in <module>
    from nvitop import Device
ModuleNotFoundError: No module named 'nvitop'
```

Signed-off-by: Shunsuke Kimura <pbrehpuum@gmail.com>