benchmarks: add build options (#1340)
> All dependencies are automatically managed by the Holohub Docker
container. You can simply run:
> ./holohub run-container [<application_name>]
> 

https://github.com/nvidia-holoscan/holohub/tree/main/benchmarks/holoscan_flow_benchmarking#holohub-docker-container-recommended

I ran run-container after reading the documentation.

Running benchmark in the container without any options results in errors
due to missing packages.

```
$ ./holohub run-container  endoscopy_tool_tracking
...
xxx@yyy:~$ python3 benchmarks/holoscan_flow_benchmarking/benchmark.py -a  endoscopy_tool_tracking  -r 3 -i 3 -m 200     --sched greedy     -d myoutputs
Traceback (most recent call last):
  File "/workspace/holohub/benchmarks/holoscan_flow_benchmarking/benchmark.py", line 27, in <module>
    from nvitop import Device
ModuleNotFoundError: No module named 'nvitop'
```

<!-- This is an auto-generated comment: release notes by coderabbit.ai
-->

## Summary by CodeRabbit

* **Documentation**
* Updated benchmarking guide with the new container execution command
syntax, which now requires build arguments to properly initialize the
benchmarking-setup environment.

<sub>✏️ Tip: You can customize this high-level summary in your review
settings.</sub>

<!-- end of auto-generated comment: release notes by coderabbit.ai -->

---------

Signed-off-by: Shunsuke Kimura <pbrehpuum@gmail.com>
Signed-off-by: B Hashemian <3968947+bhashemian@users.noreply.github.com>
Co-authored-by: B Hashemian <3968947+bhashemian@users.noreply.github.com>