App: Update object_detection_torch for PyTorch iGPU wheels
Upcoming release Holoscan SDK >=3.6.0 aims to drop torchvision as a core
Holoscan SDK dependency, however the model used in
object_detection_torch requires torchvision symbols.

For iGPU platforms we need to fetch the Jetson PyPI torch and
torchvision packages for these symbols.

Addresses link time issue:
```
/usr/bin/ld: /usr/local/lib/python3.12/dist-packages/torch/lib/../../torch.libs/libopenblasp-r0-121ca252.3.30.so: undefined reference to `_gfortran_concat_string@GFORTRAN_8'

/usr/bin/ld: /usr/local/lib/python3.12/dist-packages/torch/lib/../../torch.libs/libopenblasp-r0-121ca252.3.30.so: undefined reference to `_gfortran_etime@GFORTRAN_8'
```

Signed-off-by: Tom Birdsong <tbirdsong@nvidia.com>