App: Update "holoscan" wheel installation in colonoscopy_segmentation
Replaces previous permissions approach to instead run holoscan wheel
post-install setup in advance.

The `holoscan-cuX` bdist wheels rely on wheel-axle-runtime to run
post-installation setup in the Python3 system environment. Setup
requires certain user permissions.

Previous behavior:
- `pip install holoscan` with root permissions, no post-install setup,
  run as non-root user encounters blocking runtime error:
```
  PermissionError: [Errno 13] Permission denied: '/usr/local/lib/python3.12/dist-packages/holoscan_cu12-3.8.0.dist-info/axle.lck'
```
- `pip install holoscan` and relaxed folder permissions: post-install
  runs automatically at container runtime, no error

Updated behavior with `python3 -m site`: runs wheel-axle-runtime
post-install setup during the docker build, no permission updates
required, running as non-root user succeeds

Post-install setup does the following:
- Runs "python3.12/dist-packages/holoscan_cu12-3.8.0.pth" to initiate
  setup
- Holds "axle.lck"
- Sets up Holoscan SDK shared library binary locations
- Creates "axle.done" and removes "holoscan_cu12-3.8.0.pth" when
  complete

Reference: https://github.com/karellen/wheel-axle-runtime

Signed-off-by: Tom Birdsong <tbirdsong@nvidia.com>

co-authored-by: Alexis Girault <agirault@nvidia.com>
co-authored-by: Connor Smith <cosmith@nvidia.com>