Fix SSH X11 forwarding (#1318)
holohub does not work with --ssh-x11 option.(`MoTTY X11 proxy: No
authorisation provided`)

fixed --ssh-x11 option.

```
./holohub run body_pose_estimation --ssh-x11 --run-args="--source replayer"
...

[info] [inference.cpp:291] Inference context setup complete
MoTTY X11 proxy: No authorisation provided

Glfw Error 65550: Failed to detect any supported platform
[error] [gxf_wrapper.cpp:69] Exception occurred when starting operator: 'holoviz' - Failed to initialize glfw
[warning] [entity_executor.cpp:674] Failed to start entity [holoviz]
[warning] [greedy_scheduler.cpp:243] Error while executing entity 55 named 'holoviz': GXF_FAILURE
[error] [entity_executor.cpp:789] Entity [holoviz] must be in Started, Tick Pending, Ticking or Idle stage before stopping. Current state is StartPending
[info] [greedy_scheduler.cpp:401] Scheduler finished.
[error] [program.cpp:580] wait failed. Deactivating...
[error] [runtime.cpp:1655] Graph wait failed with error: GXF_FAILURE
[warning] [gxf_executor.cpp:2548] GXF call GxfGraphWait(context) in line 2548 of file /workspace/holoscan-sdk/src/core/executors/gxf/gxf_executor.cpp failed with 'GXF_FAILURE' (1)
[info] [gxf_executor.cpp:2563] [Body Pose Estimation App] Graph execution finished.
[error] [gxf_executor.cpp:2571] [Body Pose Estimation App] Graph execution error: GXF_FAILURE
Traceback (most recent call last):
  File "/workspace/holohub/applications/body_pose_estimation/body_pose_estimation.py", line 518, in <module>
    main()
  File "/workspace/holohub/applications/body_pose_estimation/body_pose_estimation.py", line 514, in main
    app.run()
RuntimeError: Failed to initialize glfw
[info] [gxf_executor.cpp:432] [Body Pose Estimation App] Destroying context
Non-zero exit code running command: python3 /workspace/holohub/applications/body_pose_estimation/body_pose_estimation.py --source replayer
Exit code: 1
Non-zero exit code running command: docker run --net host --interactive --tty -u 1000:1000 -v /etc/group:/etc/group:ro -v /etc/passwd:/etc/passwd:ro -v /tmp/holohub:/workspace/holohub -w /workspace/holohub --runtime nvidia --gpus all --cap-add CAP_SYS_PTRACE --ipc=host -v /dev:/dev --device-cgroup-rule "c 81:* rmw" --device-cgroup-rule "c 189:* rmw" -e NVIDIA_DRIVER_CAPABILITIES=graphics,video,compute,utility,display -e HOME=/workspace/holohub -e CUPY_CACHE_DIR=/workspace/holohub/.cupy/kernel_cache -e HOLOHUB_BUILD_LOCAL=1 --rm --ipc=host --cap-add=CAP_SYS_PTRACE --ulimit=memlock=-1 --ulimit=stack=67108864 --device /dev/snd/controlC0 --device /dev/snd/controlC1 --device /dev/snd/pcmC0D0c --device /dev/snd/pcmC0D0p --device /dev/snd/pcmC1D9p --device /dev/snd/pcmC1D8p --device /dev/snd/pcmC1D7p --device /dev/snd/pcmC1D3p --device /dev/snd/timer --device /dev/snd/seq --mount source=/etc/asound.conf,target=/etc/asound.conf,readonly,type=bind --device /dev/infiniband/rdma_cm --device /dev/infiniband/uverbs1 --device /dev/infiniband/uverbs0 --device /dev/nvidia0 --device /dev/nvidia-modeset -v /usr/share/nvidia/nvoptix.bin:/usr/share/nvidia/nvoptix.bin:ro --group-add 39 --group-add 998 --group-add 972 --group-add 63 -e XDG_RUNTIME_DIR -v /run/user/1000:/run/user/1000 -v /tmp/.X11-unix:/tmp/.X11-unix -e DISPLAY -v /tmp/.docker.xauth:/tmp/.docker.xauth -e XAUTHORITY=/tmp/.docker.xauth -e PYTHONPATH=/opt/nvidia/holoscan/python/lib:/workspace/holohub/benchmarks/holoscan_flow_benchmarking --entrypoint=/bin/bash holohub-body_pose_estimation:ee85c57cebdc -c "./holohub run body_pose_estimation --language python --local --run-args='--source replayer'"
Exit code: 1
```

<!-- This is an auto-generated comment: release notes by coderabbit.ai
-->
## Summary by CodeRabbit

* **New Features**
* Improved SSH X11 forwarding when a display is present, with automatic
handling of X authority to enable GUI apps in containers.

* **Bug Fixes**
* Added environment checks and user warnings when DISPLAY or X authority
tools are missing, and safer temporary-file handling to reduce failures
and improve security of forwarded X11 sessions.

<sub>✏️ Tip: You can customize this high-level summary in your review
settings.</sub>
<!-- end of auto-generated comment: release notes by coderabbit.ai -->

---------

Signed-off-by: Shunsuke Kimura <pbrehpuum@gmail.com>
Co-authored-by: Bruce Hashemian <3968947+bhashemian@users.noreply.github.com>