Depth Anything v2: fix build error
onnx.helper.float32_to_bfloat16 is deprecated.
<https://github.com/onnx/onnx/commit/c9d9c556425ba67ba2f64e10456f90a805f08773>

```
$ ./holohub run depth_anything_v2 --ssh-x11 --run-args="--source replayer"

...
6.119 Saving to: 'graph_surgeon.py'
6.119
6.119      0K .                                                     100% 65.3M=0s
6.119
6.119 2025-12-15 06:35:52 (65.3 MB/s) - 'graph_surgeon.py' saved [1452/1452]
6.119
6.255 Traceback (most recent call last):
6.255   File "/app/Depth-Anything-V2/./graph_surgeon.py", line 22, in <module>
6.255     import onnx_graphsurgeon as gs
6.255   File "/usr/local/lib/python3.12/dist-packages/onnx_graphsurgeon/__init__.py", line 1, in <module>
6.255     from onnx_graphsurgeon.exporters.onnx_exporter import export_onnx
6.255   File "/usr/local/lib/python3.12/dist-packages/onnx_graphsurgeon/exporters/onnx_exporter.py", line 134, in <module>
6.255     np.uint16, onnx.helper.float32_to_bfloat16
6.255                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
6.255 AttributeError: module 'onnx.helper' has no attribute 'float32_to_bfloat16'
```

work around here <https://github.com/NVIDIA/TensorRT/issues/4635>

Signed-off-by: Shunsuke Kimura <pbrehpuum@gmail.com>