App: Update `colonoscopy_segmentation` README (#1066)
* App: Update `colonoscopy_segmentation` README

Update `colonoscopy_segmentation` README in response to internal
feedback.

Signed-off-by: Tom Birdsong <tbirdsong@nvidia.com>

* App: colonoscopy_segmentation Dockerfile updates

Addresses observed issues:
- Docker build: Debian frontend defaults to "teletype" rather than
  "noninteractive" during apt install
- App runtime: observed CuPy NVRTC failures due to missing CUDA math headers

```
cupy_backends.cuda.libs.nvrtc.NVRTCError: NVRTC_ERROR_COMPILATION (6)
...
cupy.cuda.compiler.CompileException: /usr/local/lib/python3.12/dist-packages/cupy/_core/include/cupy/carray.cuh(57): catastrophic error: cannot open source file "cuda_fp16.h"
```

Signed-off-by: Tom Birdsong <tbirdsong@nvidia.com>

* Update for mode presets

Signed-off-by: Tom Birdsong <tbirdsong@nvidia.com>

---------

Signed-off-by: Tom Birdsong <tbirdsong@nvidia.com>