Fixes for `vila_live` build
Updates to fix `vila_live` build errors following HoloHub default
generator update to Ninja.

Addresses errors on x86 platform:

Docker build:
```bash
0.454 Collecting flash-attn~=2.5
0.694   Downloading flash_attn-2.7.4.post1.tar.gz (6.0 MB)
1.893      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 6.0/6.0 MB 5.3 MB/s eta 0:00:00
2.687   Preparing metadata (setup.py): started
2.746   Preparing metadata (setup.py): finished with status 'error'
2.748   error: subprocess-exited-with-error
2.748
2.748   × python setup.py egg_info did not run successfully.
2.748   │ exit code: 1
2.748   ╰─> [6 lines of output]
2.748       Traceback (most recent call last):
2.748         File "<string>", line 2, in <module>
2.748         File "<pip-setuptools-caller>", line 34, in <module>
2.748         File "/tmp/pip-install-yjwnc8sl/flash-attn_42b07c7ef9e64ab497235f9174b57d88/setup.py", line 12, in <module>
2.748           from packaging.version import parse, Version
2.748       ModuleNotFoundError: No module named 'packaging'
```

CMake build:
```sh
[command] cmake --build build/vila_live -j
ninja: error: build.ninja:1440: multiple rules generate /workspace/holohub/data/vila_live/meeting.gxf_index
```

A runtime error is observed and requires further investigation:
```sh
ImportError: cannot import name 'is_torch_greater_or_equal_than_1_13' from 'transformers.pytorch_utils' (/usr/local/lib/python3.10/dist-packages/transformers/pytorch_utils.py)
```

Signed-off-by: Tom Birdsong <tbirdsong@nvidia.com>