Revert "Bump transformers (#734)"
This reverts commit 0cd5a30a6379314f684be49df462f2c56b4dbade.

Addresses issue after upgrade:
```
ImportError: cannot import name 'is_torch_greater_or_equal_than_1_13' from 'transformers.pytorch_utils' (/usr/local/lib/python3.10/dist-packages/transformers/pytorch_utils.py)
```

Signed-off-by: Tom Birdsong <tbirdsong@nvidia.com>